#include "pieces.h"

int main(void)
{
	int board[8][8] =
	{
		{ WHITE_ROOK, WHITE_KNIGHT, WHITE_BISHOP, WHITE_QUEEN, WHITE_KING,   WHITE_BISHOP, WHITE_KNIGHT, WHITE_ROOK },
		{ WHITE_PAWN, WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,  WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN,   WHITE_PAWN },
		{ EMPTY_SQR,  EMPTY_SQR,    EMPTY_SQR, 	  EMPTY_SQR,   EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR  },
 		{ EMPTY_SQR,  EMPTY_SQR,    EMPTY_SQR, 	  EMPTY_SQR,   EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR  },
   		{ EMPTY_SQR,  EMPTY_SQR,    EMPTY_SQR, 	  EMPTY_SQR,   EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR  },
 		{ EMPTY_SQR,  EMPTY_SQR,    EMPTY_SQR, 	  EMPTY_SQR,   EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR,    EMPTY_SQR  },
 		{ BLACK_PAWN, BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,  BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN,   BLACK_PAWN },
 		{ BLACK_ROOK, BLACK_KNIGHT, BLACK_BISHOP, BLACK_QUEEN, BLACK_KING,   BLACK_BISHOP, BLACK_KNIGHT, BLACK_ROOK }
	};
	return 0;
}
